# Copyright 2019 Tricot Inc.
# Use of this source code is governed by the license in the LICENSE file.

version: 2
jobs:
  build:
    docker:
        - image: tricot/build-public-circleci:4.0.0

    working_directory: ~/bazel2x

    steps:
      - checkout

      # Gofmt:
      - run: gofmt-check-all.sh

      ### Restore cache:

      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "go.sum" }}-{{ .Revision }}
          - v2-dependencies-{{ checksum "go.sum" }}-
          - v2-dependencies-

      ### Main Go stuff:

      # Go vet:
      - run: go vet -composites=false ./...

      # Go build:
      - run: go build -v ./...

      # Go tests:
      - run: go test -v ./...

      ### Save cache:

      - save_cache:
          paths:
            - /go/pkg/mod
          key: v2-dependencies-{{ checksum "go.sum" }}-{{ .Revision }}
